Step2
next-step/java-qna-atdd pull request #118
Opened 2019-04-01 04:32 UTC by yesjehmi

2019-04-01 11:40 UTC, javajigi requested changes
Acceptance Test 추가하는 것이 쉽지 않을텐데 구현 잘 했네요. 👍 
단, 로직 구현을 db 쿼리를 통해 구현하려고 하는데요. 그 보다 애플리케이션 로직을 통해 구현해볼 것을 추천해요.

2019-04-01 11:40 UTC, javajigi commented on src/main/java/nextstep/domain/QuestionRepository.java
> +    Optional<Question> findFirstByTitleAndContents(String title, String contents);
테스트를 위한 이 메소드 없이 구현 진행해 본다.

2019-04-01 11:40 UTC, javajigi commented on src/main/java/nextstep/domain/QuestionRepository.java
> +    Optional<Question> findByIdAndWriter(Long id, User writer);
이 메소드 없이 구현 진행해 본다.

2019-04-01 11:40 UTC, javajigi commented on src/main/java/nextstep/domain/QuestionRepository.java
> +    void deleteByIdAndWriter(Long id, User writer);
이 메소드 없이 구현 진행해 본다.

2019-04-01 11:40 UTC, javajigi commented on src/main/java/nextstep/domain/QuestionRepository.java
>  }
db 쿼리를 통해 로직을 구현하기 보다 애플리케이션 로직을 통해 같은 기능을 구현해 본다.

2019-04-01 11:40 UTC, javajigi commented on src/main/java/nextstep/service/QnaService.java
> +        updatedQuestion.writeBy(loginUser);
사용자가 전달한 updatedQuestion을 기반으로 기능을 구현하는 것은 문제가 발생할 가능성이 있다. 이 문제점이 무엇인지 찾아본다.
updatedQuestion을 이용하기 보다 db에서 Question을 조회한 후 이 객체를 업데이트하는 방식으로 구현한다.

2019-04-01 11:40 UTC, javajigi commented on src/test/java/nextstep/web/UserAcceptanceTest.java
> +                                    .addParameter("_method", "put")
HtmlFormDataBuilder에 put() 메소드를 추가해 다음과 같이 구현하도록 하면 어떨까?

```
HtmlFormDataBuilder.urlEncodedForm().put()...
```

delete 요청도 같다.

2019-04-01 22:27 UTC, javajigi requested changes
피드백 반영 잘 했네요. 👍 
추가로 개선했으면 하는 내용이 있어 피드백 좀 남겼어요.

2019-04-01 22:27 UTC, javajigi commented on src/main/java/nextstep/domain/Question.java
> +    public boolean isWriter(User user) {
isOwner 메소드를 제공하고 있어 추가로 구현하지 않아도 됨

2019-04-01 22:27 UTC, javajigi commented on src/main/java/nextstep/domain/Question.java
> +    public void delete() {
자신이 쓴 글인지에 대한 확인을 이 메소드에서 하는 것은 어떨까?

2019-04-01 22:27 UTC, javajigi commented on src/main/java/nextstep/service/QnaService.java
> +        return questionRepository.save(question);
set 메소드 사용을 지양한다.
다음과 같이 구현하는 것은 어떨까?

```
question.update(loginUser, updatedQuestion);
```

questionRepository.save(..)와 같이 명시적으로 구현하지 않고 단순히 question.update(loginUser, updatedQuestion)만으로도 수정이 가능한지 테스트해 본다.

2019-04-01 22:27 UTC, javajigi commented on src/main/java/nextstep/service/QnaService.java
> +        questionRepository.save(question);
questionRepository.save(..)와 같이 명시적으로 구현하지 않고 단순히 question.delete()만으로도 수정이 가능한지 테스트해 본다.

2019-04-01 22:27 UTC, javajigi commented on src/main/java/nextstep/web/QnaController.java
> +            return "redirect:/"+id;
space convention 위반

2019-04-02 06:03 UTC, yesjehmi commented on src/main/java/nextstep/service/QnaService.java
> +        questionRepository.save(question);
음 이부분은 제가 잘 이해가 안가는데 다시한번 설명 부탁드려두될까요..
삭제를 위해서는 repository에서의 변경사항 저장 방식이 필요한데 
그걸 도메인 메소드 내부에서 처리하는게 어떤식으로 가능한건지 이해가 잘 가지 않습니다..

2019-04-02 14:38 UTC, kang-hyungu commented on src/main/java/nextstep/service/QnaService.java
> +        questionRepository.save(question);
jpa에서는 엔티티 변경사항을 데이터베이스에 자동으로 반영하는 변경 감지(dirty checking)이라는 기능이 있습니다.
트랜잭션 내에서 엔티티를 조회(꼭 조회해야합니다)해서 데이터를 변경하면 자동으로 update 쿼리를 수행합니다.
좀더 상세한 내용은 자바 ORM 표준 JPA 프로그래밍(저자 김영한) 102쪽 엔티티 수정을 참고하시기 바랍니다.

2019-04-02 14:46 UTC, kang-hyungu commented on src/main/java/nextstep/service/QnaService.java
> +        questionRepository.save(question);
update 쿼리가 동작하는지 확인하려면 questionRepository.save(question)를 주석처리하여 앱을 띄우고 콘솔창에서 어떤 쿼리가 실제로 실행되는지 확인해보시기 바랍니다.

2019-04-02 14:58 UTC, kang-hyungu commented on src/main/java/nextstep/service/QnaService.java
> +        questionRepository.save(question);
update 쿼리가 동작하는지 확인하려면 questionRepository.save(question)를 주석처리하여 앱을 띄우고 콘솔창에서 어떤 쿼리가 실제로 실행되는지 확인해보시기 바랍니다.

2019-04-03 02:29 UTC, elie-jehmi commented on src/main/java/nextstep/service/QnaService.java
> +        questionRepository.save(question);
와우 전에 들어본개념이었는데 jpa 많이 사용을 안해봐서 잊고있었네요.....ㅋㅋ
자세한 설명 감사합니다!!^__^

2019-04-03 13:05 UTC, kang-hyungu approved these changes
코드 수정하신 내용 확인했습니다.
구현 하느라 수고하셨습니다!
다음 단계 진행하시죠

2019-04-03 13:05 UTC, kang-hyungu commented on src/main/java/nextstep/domain/Question.java
> +        if ( !isOwner(loginUser)) {
의도하신 띄어쓰기일까요?
코드 읽을 때 !가 잘 안보여서 괄호 사이에 띄어쓰기를 하는 경우도 있습니다.
지금은 연습 과정이니 컨벤션에 맞춰서 공백을 지워주세요!

2019-04-03 13:05 UTC, merged