Step2 요구사항 구현
next-step/java-qna-atdd pull request #119
Opened 2019-04-01 13:18 UTC by namjunemy

* step1의 로그인 기능과
* step2의 question관련 기능을 구현했습니다.
* atdd 개념이 처음이라 낯설었는데요,, 피드백 부탁드리겠습니다 :)

2019-04-01 15:11 UTC, phs1116 requested changes
안녕하세요. 리뷰를 맡게된 리뷰어 박현식입니다. :)
구현 및 테스트 전체적으로 잘하신 것 같아요 👍 
더 테스트를 했으면 하는 부분이랑 피드백 사소한거 몇개 추가했습니다.
참고해주시고 궁금하신 점 있으시면 연락주세요. :)

2019-04-01 15:11 UTC, phs1116 commented on src/test/java/nextstep/service/QnaServiceTest.java
> +public class QnaServiceTest extends BaseTest {
QnaService  나머지 기능들도 테스트 작성해보는건 어떨까요? (update, delete 등)

2019-04-01 15:11 UTC, phs1116 commented on src/main/java/nextstep/web/HomeController.java
> +        List<Question> questions = qnaService.findAll(PageRequest.of(page - 1, size));
지금 구현이면 삭제된 글도 출력 될 것 같네요. :)
JPA 할 줄 아신다면 조금 수정해보면 어떨까요?

2019-04-01 15:11 UTC, phs1116 commented on src/main/java/nextstep/service/UserService.java
>      public User login(String userId, String password) throws UnAuthenticationException {
UserService  유닛테스트가 없는거 같은데 작성해보면 어떨까요? :)

2019-04-01 15:11 UTC, phs1116 commented on src/main/java/nextstep/web/QuestionController.java
> +
공백을 준 부분, 아닌 부분이 메서드마다 다르게 있는거 같은데요, 다른 매서들과 맞춰서 의미 없는 공백은 없애는게 좋을 것 같습니다. :)

2019-04-01 15:11 UTC, phs1116 commented on src/test/java/support/helper/HtmlFormDataBuilder.java
> +    public HtmlFormDataBuilder delete() {
👍

2019-04-01 15:11 UTC, phs1116 commented on src/main/java/nextstep/web/QuestionController.java
> +        Question question = qnaService.findById(id)
현재 구현 상 삭제 된 글도 출력이 되며, 수정도 가능합니다. :)
이것도 수정해보면 어떨까요?

2019-04-01 15:11 UTC, phs1116 commented on src/test/java/nextstep/service/QnaServiceTest.java
> +        User loginUser = new User("namjunemy", "1234", "njkim", "njkim@slipp.net");
공통적으로 사용하는 테스트 변수라면 상수로 빼서 사용해도 되지 않을까요?
Question도 공통적인 코드는 따로 빼도 될 것 같습니다. :)

2019-04-01 17:52 UTC, namjunemy commented on src/main/java/nextstep/web/QuestionController.java
> +
반영헀습니다:)

2019-04-02 09:47 UTC, namjunemy commented on src/test/java/nextstep/service/QnaServiceTest.java
> +public class QnaServiceTest extends BaseTest {
QnaService 테스트 코드 반영했습니다!

2019-04-02 09:49 UTC, namjunemy commented on src/main/java/nextstep/service/UserService.java
>      public User login(String userId, String password) throws UnAuthenticationException {
test/service/UserServiceTest 에 구현되어있습니다!

2019-04-02 09:58 UTC, namjunemy commented on src/test/java/nextstep/service/QnaServiceTest.java
> +        User loginUser = new User("namjunemy", "1234", "njkim", "njkim@slipp.net");
setup 메소드로 중복코드를 제거했습니다 :)

2019-04-02 10:37 UTC, namjunemy commented on src/main/java/nextstep/web/HomeController.java
> +        List<Question> questions = qnaService.findAll(PageRequest.of(page - 1, size));
findAllByDeleted()를 구현해서 deleted된 데이터들은 조회하지 않도록 구현했는데,
혹시 올바르게 구현한것이 맞나요? 이부분은 서치해도 정보가 많이 없네요..

2019-04-02 10:37 UTC, namjunemy commented on src/main/java/nextstep/web/QuestionController.java
> +        Question question = qnaService.findById(id)
삭제된 데이터는 출력/수정/삭제가 되지 않도록 구현했고, 이에 따른 테스트 코드들을 추가했습니다:)

2019-04-02 17:26 UTC, phs1116 commented on src/main/java/nextstep/web/HomeController.java
> +        List<Question> questions = qnaService.findAll(PageRequest.of(page - 1, size));
앗 JPA 하시는 줄 알았어요 :) 네 잘하셨습니다. 👍

2019-04-02 17:29 UTC, phs1116 approved these changes
안녕하세요. 리뷰어 박현식입니다. :)
전체적으로 테스트 구현 너무 잘하셨어요 👍 
두가지 피드백 추가했는데 이건 다음 단계 진행하시면서 보시면 될 것 같습니다.
2단계 구현하시느라 수고 많으셨습니다. :)

2019-04-02 17:29 UTC, phs1116 commented on src/test/java/nextstep/service/QnaServiceTest.java
> +        qnaService.update(loginUser, 1L, new Question("제목 수정", "내용 수정"));
question이 "제목 수정", "내용 수정"로  update 됬는지도 검증할 수 있지 않을까요? :)

2019-04-02 17:29 UTC, phs1116 commented on src/test/java/nextstep/service/QnaServiceTest.java
> +        qnaService.deleteQuestion(loginUser, 1L);
마찬가지로 question.isDeleted() 를 통해 삭제 여부도 검증 할 수 있지 않을까요? :)

2019-04-02 17:29 UTC, merged