Step2 구현
next-step/java-qna-atdd pull request #125
Opened 2019-04-02 09:18 UTC by joont92

안녕하세요! Step2 구현했습니다.
AcceptanceTest 검증 부분이 조금 어렵네요. 처음에는 디비에 값 넣고 출력되는 문자열을 체크했는데.. 이래저래 걸리는게 많아서 대부분 제거했습니다.

리뷰 부탁드립니다. 감사합니다!

2019-04-02 17:14 UTC, phs1116 requested changes
안녕하세요. 리뷰를 맡게 된 리뷰어 박현식이라고 합니다. :)
구현 전체적으로 깔끔하게 잘 하셨어요 👍 
피드백 몇가지 추가했어요.
참고해주시고 궁금하신 점 있으시면 언제든지 연락주세요. :)

2019-04-02 17:14 UTC, phs1116 commented on src/main/java/nextstep/service/QnAService.java
> +        question.setTitle(updatedQuestion.getTitle());
`객체지향 생활체조 규칙 9: 게터/세터/프로퍼티를 쓰지 않는다.`
question.update(updatedQuestion) 형태로 구현해보면 어떨까요?

2019-04-02 17:14 UTC, phs1116 commented on src/main/java/nextstep/web/QuestionController.java
> +        if(!result.isOwner(user)) {
findByOwner 구현해놓으신거 있는데 그걸 사용해보면 어떨까요?

2019-04-02 17:14 UTC, phs1116 commented on src/main/java/nextstep/web/QuestionController.java
> +        List<Question> list = qnAService.findAll();
redirect도 고려해보면 어떨까요?

2019-04-02 17:14 UTC, phs1116 commented on src/test/java/nextstep/domain/QuestionTest.java
> +    public void 작성자가_맞는지_확인한다() {
Question 삭제, 수정에 대한 테스트도 추가해보면 어떨까요?
그 외 다른 현재 요구사항에 있는 Service나 현재 있는 객체들도 찾아보시고 테스트 해보시면 좋을 것 같습니다. :)

2019-04-02 17:14 UTC, phs1116 commented on src/test/java/nextstep/service/QnAServiceTest.java
> +    public void 질문을_수정한다() {
작성자가 아니면 질문을 수정할수 없는 것, 삭제할 수 없는 것에 대한 테스트도 추가되면 좋을 것 같아요. :)

2019-04-02 17:14 UTC, phs1116 commented on src/test/java/nextstep/web/QuestionAcceptanceTest.java
> +    public void 로그인한_사용자만_질문_등록폼에_들어갈수_있다() {
예외 상황들에 대한 케이스들도 추가하면 좋을 것 같습니다. :)

2019-04-02 17:14 UTC, phs1116 commented on src/main/java/nextstep/service/QnAService.java
> +        return questionRepository.findById(id).orElseThrow(NotFoundException::new);
현재 구현이면 삭제된 글도 조회가 될 것 같아요 :)

2019-04-03 08:23 UTC, joont92 commented on src/main/java/nextstep/service/QnAService.java
> +        question.setTitle(updatedQuestion.getTitle());
감사합니다!

2019-04-03 08:31 UTC, joont92 commented on src/main/java/nextstep/web/QuestionController.java
> +        if(!result.isOwner(user)) {
변경했습니당~~

2019-04-03 08:32 UTC, joont92 commented on src/main/java/nextstep/web/QuestionController.java
> +        List<Question> list = qnAService.findAll();
그 생각을 못했네요. 감사합니다

2019-04-03 08:53 UTC, joont92 commented on src/test/java/nextstep/service/QnAServiceTest.java
> +    public void 질문을_수정한다() {
추가하였습니다

2019-04-03 08:55 UTC, joont92 commented on src/test/java/nextstep/web/QuestionAcceptanceTest.java
> +    public void 로그인한_사용자만_질문_등록폼에_들어갈수_있다() {
반영해서 추가하였습니다만.. 이 부분은 `@LoginUser` 에 대한 테스트라 기존에 넣지 않았었는데요, 이런 부분까지 원래는 작성해주는게 좋을까요?

2019-04-03 09:21 UTC, joont92 commented on src/main/java/nextstep/service/QnAService.java
> +        return questionRepository.findById(id).orElseThrow(NotFoundException::new);
엔티티에 추가하였습니다

2019-04-03 09:24 UTC, joont92 commented on src/test/java/nextstep/domain/QuestionTest.java
> +    public void 작성자가_맞는지_확인한다() {
음.. 당장은 보이는게 많이 없네요 ㅠㅠ 일단 update 테스트만 추가했습니다

2019-04-03 11:58 UTC, phs1116 requested changes
안녕하세요! 리뷰어 박현식입니다. :) 
피드백 반영해주셔서 감사합니다 ㅎㅎ
테스트 추가 👍 
마지막으로 몇가지 피드백 추가했어요.
피드백 보시구 궁금하신점 있으시면 언제든지 연락주세요. :)

2019-04-03 11:58 UTC, phs1116 commented on src/main/java/nextstep/service/QnAService.java
> +        questionRepository.delete(question);
앗 지금 보니 hard delete를 하고 계시네요.
직접적으로 지우지 마시고 Question의 delete를 통한 soft delete로 구현해보시겠어요? :)
그리고  delete에 대한 테스트도 추가시면 될 것 같습니다. :)

2019-04-03 11:58 UTC, phs1116 commented on src/test/java/nextstep/domain/QuestionTest.java
> +    public void 작성자가_맞는지_확인한다() {
삭제에 대한 테스트도 있을 것 같아요.
작성자가 아니면 삭제, 수정을 못한다 정도의 테스트가 추가 될 수 있겠네요. :)
예외 상황에 대한 테스트도 같이 추가해주세요! ㅎㅎ :)

2019-04-03 11:58 UTC, phs1116 commented on src/test/java/nextstep/web/QuestionAcceptanceTest.java
> +    public void 로그인한_사용자만_질문_등록폼에_들어갈수_있다() {
네 @LoginUser의 테스트랑은 조금 다른 부분이에요 ㅎㅎ
이 기능에서 LoginUser 어노테이션을 잘 사용하고있는지에 대한 테스트라고 보시면 될 것 같습니다. :)
실수로 개발 도중 해당 어노테이션을 지울 경우에는 로그인 하지 않는 유저 또한 해당 컨트롤러에 접근이 가능하게 되는데,
이 테스트가 있다면 이런 실수를 방지 할 수 있겠죠? :)

2019-04-03 15:20 UTC, joont92 commented on src/main/java/nextstep/service/QnAService.java
> +        questionRepository.delete(question);
반영했습니다!

2019-04-03 15:23 UTC, joont92 commented
피드백 감사드립니다! 
QuestionTest에 대한 피드백 보고 조금 궁금한것이 있어서 추가 질문드립니다
update, delete에 대한 테스트(+예외 테스트)는 기존에 QnAServiceTest에 들어있었는데요, 혹시 말씀하신게 이 기능들이 Question 내부로 들어가는게 좋다는 말씀이신가요?
만약 맞다면.. update는 그렇게 변경 가능한데 delete는 어떻게 테스트 할 수 있나요? ㅠㅠ

2019-04-04 12:08 UTC, phs1116 requested changes
안녕하세요! 리뷰어 박현식입니다.
질문해주신 부분에 대해서 피드백 추가했습니다.
확인 부탁드려요!! :)

2019-04-04 12:08 UTC, phs1116 commented on src/main/java/nextstep/service/QnAService.java
> +        questionRepository.delete(question);
questionRepository.delete를 통해 db 내에서 물리적으로 지우는 것을 하드딜리트라고 합니다 :)
Question에 있는 deleted =  true로 명시적으로 설정해서 지웠다는 의미만 표현하는걸 소프트 딜리트라고 부르구요!
향후 과제를 위해 소프트 딜리트로 수정하시는게 좋을 듯 합니다. :)
question.delete(loginuser); 이렇게 될 수 있겠죠?

현재는 QnaService가 단순해서 그냥  Question을 호출하는 형태지만,
비즈니스 요구사항이 추가되서 QnaService에도 로직이 추가될 경우에는 다른 테스트가 됩니다 :) 
그래서 둘 다 테스트 해주는 것이 좋습니다.

2019-04-04 13:56 UTC, phs1116 approved these changes
안녕하세요! 리뷰어 박현식입니다. :) 
마지막 피드백 잘 받아주셔서 감사합니다. 
2단계 머지할게요.
구현하시느라 수고 많으셨습니다. :)

2019-04-04 13:56 UTC, merged