Step4 요구사항 구현
next-step/java-qna-atdd pull request #140
Opened 2019-04-06 19:18 UTC by namjunemy

* step3의 JPA 관련 피드백을 생각해보다가, answer를 삭제할때마다 전체 answer를 삭제하는 로직이 불필요하다고 판단했습니다. 자세히는 question에서 @OneToMany로 참조하는데 굳이 answer를 delete하는 시점에 question을 먼저 조회하고, answer를 다시 조회해서 지우는 작업을 제거하면서 그에 맞게 수정했습니다.
* step4의 요구사항을 구현하면서 필요없는 테스트코드를 삭제하고, 새로 필요한 테스트코드를 추가했습니다.
* 피드백 요청드립니다 :)

2019-04-07 08:07 UTC, phs1116 requested changes
안녕하세요. 리뷰어 박현식입니다. :)
4단계 요구사항 구현 너무 잘하신 것 같아요 👍 
테스트코드도 중복 값에 대한 상수처리 👍 
몇가지 피드백 추가했는데요. 
한번 참고해주시고 궁금하신거 있으시면 연락주세요. :)

2019-04-07 08:07 UTC, phs1116 commented on src/main/java/nextstep/domain/Question.java
> +    private List<DeleteHistory> deleteAllAnswers(User requestUser) {
Answer에 대한 로직이 Question에 일부 추가 된 것 같은데요.
List<Answer> answers를 일급콜렉션으로 분리해보면 어떨까요? 그럼 뭐가 달라질까요?

2019-04-07 08:07 UTC, phs1116 commented on src/main/java/nextstep/domain/Question.java
>      public Question update(User loginUser, Question target) {
Quenstion을 변경할 때 마다 Question자체를 받는데요,
실제 이 update를 사용할 때마다 변경되는 부분은 정해져있습니다.
이 부분만 따로 추상화해보면 어떨까요? 그럼 컨트롤러부터 전체적으로 어떤식으로 바뀔까요? :)

2019-04-07 08:07 UTC, phs1116 commented on src/main/java/nextstep/web/ApiQuestionController.java
> +        headers.setLocation(URI.create("/api" + createdAnswer.generateUrl()));
"/api"라는 부분이 사용빈도도 높은데도 불구하고 하드코딩 되어있는데요, 상수로 분리해보면 어떨까요?

2019-04-07 08:07 UTC, phs1116 commented on src/test/java/nextstep/web/ApiQuestionAcceptanceTest.java
> +        ResponseEntity<Void> responseEntity =
HttpStatus에 대한 검증도 추가되면 좋지 않을까요?
API 스펙에 HttpStatus도 작성하기도 하거든요 :)

2019-04-07 16:50 UTC, namjunemy commented on src/test/java/nextstep/web/ApiQuestionAcceptanceTest.java
> +        ResponseEntity<Void> responseEntity =
제가 status 검증을 놓쳤었군요..! 반영했습니다:)

2019-04-07 16:56 UTC, namjunemy commented on src/main/java/nextstep/web/ApiQuestionController.java
> +        headers.setLocation(URI.create("/api" + createdAnswer.generateUrl()));
반영했습니다:)

2019-04-07 17:15 UTC, namjunemy commented on src/main/java/nextstep/domain/Question.java
>      public Question update(User loginUser, Question target) {
해당 부분만 DTO로 전달받아서 처리했습니다.
테스트 코드에서도 update를 위해 originalQuestion의 아이디를 set해서 새로 만드는 newQuestion 클래스를 매번 만들지 않아되 되서 더 간결해졌습니다:)

2019-04-07 18:00 UTC, namjunemy commented on src/main/java/nextstep/domain/Question.java
> +    private List<DeleteHistory> deleteAllAnswers(User requestUser) {
일급컬렉션으로 변경했더니 Question 엔티티 클래스의 복잡도가 줄었습니다.

2019-04-08 10:35 UTC, phs1116 requested changes
안녕하세요. 리뷰어 박현식입니다.
피드백 잘 반영해주셔서 감사합니다 :) 
마지막으로 피드백 하나만 딱 추가했는데요.
확인 부탁드릴게요. :) 
혹시나 이해 안가시는 점 있으시면 언제든지 DM 주세요.

2019-04-08 10:35 UTC, phs1116 commented on src/main/java/nextstep/domain/Question.java
>      public Question update(User loginUser, Question target) {
한가지만 더 개선해볼게요 :)
변경이 많은 부분 (title, contents) 부분만 하나의 값객체로 만들어서
엔티티가 가지고 있도록 해보면 어떨까요?
변경도 이 값객체를 변경함으로써 변경하도록 하면 어떨까요?

2019-04-08 14:05 UTC, namjunemy commented
Question의 body 부분을 VO로 분리했는데요,
구현이 피드백 의도에 맞는지 궁금합니다. 또는 더 낳은 방법이 있다면 피드백 부탁 드릴게요:)

2019-04-09 10:38 UTC, phs1116 approved these changes
안녕하세요. 리뷰어 박현식입니다. :)
QuestionBody 추상화 👍 
4단계 머지할게요.
4단계까지 개발하시느라 정말 수고 많으셨습니다. :)
아 그리고 질문 하신 사항에 대해서 다른 방법에 대해서 댓글 하나 남겼는데 참고해주세요 :)

2019-04-09 10:38 UTC, phs1116 commented on src/main/java/nextstep/domain/Question.java
>      public Question update(User loginUser, Question target) {
값객체는 일반적으로 immutable하게 작성해요 :)
DTO보다는 QuestionBody를 전달받아서 이를 변경하는 방식도 괜찮을 것 같아요. :)

2019-04-09 10:38 UTC, merged