#step4 기능구현
next-step/java-qna-atdd pull request #152
Opened 2019-04-12 00:31 UTC by willing1026

피드백 부탁드립니다!

2019-04-13 09:57 UTC, kang-hyungu requested changes
안녕하세요 선호님
간단히 몇 가지 피드백 남기고 질문 주신 내용에도 답변 남겼어요
그리고 ApiQuestionAcceptanceTest에서 깨지는 다른 두 테스트도 확인해주세요
수정하시고 알려주시면 머지 할게요!

2019-04-13 09:57 UTC, kang-hyungu commented on src/main/java/nextstep/domain/entity/DeleteHistory.java
> +            deleteHistories.add(new DeleteHistory(ContentType.ANSWER, answer.getId(), answer.getWriter()));
answer.getWriter()로 구현한 이유는 답변 작성자만 삭제 가능해서 일까요?

2019-04-13 09:57 UTC, kang-hyungu commented on src/main/java/nextstep/domain/entity/Question.java
> +        for (Answer answer : answers) {
answers.stream.anyMatch를 사용하면 더 간결해질거에요

2019-04-13 09:57 UTC, kang-hyungu commented on src/main/java/nextstep/service/DeleteHistoryService.java
> +    @Transactional(propagation = Propagation.REQUIRES_NEW)
Propagation.REQUIRES_NEW으로 설정한 이유가 있을까요?
이 설정은 현재 트랜잭션을 멈추고 새로운 트랜잭션을 생성하는 설정인데... 필요한 옵션일까요?

2019-04-13 09:57 UTC, kang-hyungu commented on src/main/java/nextstep/service/QnaService.java
>          return findQuestionById(id)
2번 조회할 필요 없이 deleteQuestion을 반환해도 동일한 결과가 나올거에요

2019-04-13 09:57 UTC, kang-hyungu commented on src/test/java/nextstep/web/ApiAnswerAcceptanceTest.java
> +        Answer answer = getResourceWithLogin(location, Answer.class, defaultUser());
jackson에서 json 형태로 파싱할 때 getter를 사용하는데 question에 대한 getter가 없어서 null로 처리했네요.
question getter는 추가하지 마세요. 추가하면 무한 n + 1에 빠져서 에러 발생할거에요

2019-04-14 01:09 UTC, willing1026 commented on src/test/java/nextstep/web/ApiAnswerAcceptanceTest.java
> +        Answer answer = getResourceWithLogin(location, Answer.class, defaultUser());
아... 감사합니다!

2019-04-14 01:12 UTC, willing1026 commented on src/main/java/nextstep/service/QnaService.java
>          return findQuestionById(id)
정리했습니다!
deleteHistory save기능 추가하면서 코드 중복이 생겼네요;;

2019-04-14 01:24 UTC, willing1026 commented on src/main/java/nextstep/domain/entity/Question.java
> +        for (Answer answer : answers) {
크... 감사합니다 수정했습니다 👍

2019-04-14 01:40 UTC, willing1026 commented on src/main/java/nextstep/domain/entity/DeleteHistory.java
> +            deleteHistories.add(new DeleteHistory(ContentType.ANSWER, answer.getId(), answer.getWriter()));
@kang-hyungu
네네 결국 `질문작성자==답변작성자`인 경우만 삭제가 가능해서 그렇게 작성했어요
현구님은 이런경우 어떻게 구현하시는지 알려주실 수 있으세요? 🙇

2019-04-14 09:53 UTC, kang-hyungu commented on src/main/java/nextstep/domain/entity/DeleteHistory.java
> +            deleteHistories.add(new DeleteHistory(ContentType.ANSWER, answer.getId(), answer.getWriter()));
모든 권한을 가진 관리자가 삭제할 수 있지도 않을까요?
User 객체를 전달 받아서 아이디를 저장하는게 확실해보여서요

2019-04-14 10:00 UTC, kang-hyungu commented on src/main/java/nextstep/domain/entity/Question.java
> +        for (Answer answer : answers) {
반영된 코드는 anyMatch로 되어있네요
이전에 작성해주신 foreach문도 결국은 하나라도 답변 소유자가 아니면 삭제 못하도록 작성해주셔서 anyMatch와 동일하다고 생각했어요.

2019-04-14 10:14 UTC, kang-hyungu approved these changes
피드백 반영된 내용 확인하고 질문 주신 내용은 코멘트 남겼어요
테스트는 질문용으로 만드신 테스트 제외하고 모두 성공해서 개발 완료한걸로 보고 머지할게요
qna atdd 마지막 단계까지 구현하느라 수고하셨습니다 :+1:

2019-04-14 20:56 UTC, javajigi approved these changes
qna 미션 진행하느라 수고했어요.
오늘부터 제가 리뷰 진행하고 있어 최종 merge는 제가 합니다.

2019-04-14 20:57 UTC, merged